package com.example.zhangtianning.download.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.zhangtianning.download.dao.DownloadFileInfo;

import com.example.zhangtianning.download.dao.DownloadFileInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadFileInfoDaoConfig;

    private final DownloadFileInfoDao downloadFileInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadFileInfoDaoConfig = daoConfigMap.get(DownloadFileInfoDao.class).clone();
        downloadFileInfoDaoConfig.initIdentityScope(type);

        downloadFileInfoDao = new DownloadFileInfoDao(downloadFileInfoDaoConfig, this);

        registerDao(DownloadFileInfo.class, downloadFileInfoDao);
    }
    
    public void clear() {
        downloadFileInfoDaoConfig.getIdentityScope().clear();
    }

    public DownloadFileInfoDao getDownloadFileInfoDao() {
        return downloadFileInfoDao;
    }

}
