package com.example.zhangtianning.download.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWNLOAD_FILE_INFO.
 */
public class DownloadFileInfo {

    private Long id;
    private Long fileSize;
    private String filePath;
    private String fileName;
    private String tempFilePath;
    private String downloadUrl;
    private Long hadDownloadSize;
    private Integer downloadProgress;
    private Integer version;

    public DownloadFileInfo() {
    }

    public DownloadFileInfo(Long id) {
        this.id = id;
    }

    public DownloadFileInfo(Long id, Long fileSize, String filePath, String fileName, String tempFilePath, String downloadUrl, Long hadDownloadSize, Integer downloadProgress, Integer version) {
        this.id = id;
        this.fileSize = fileSize;
        this.filePath = filePath;
        this.fileName = fileName;
        this.tempFilePath = tempFilePath;
        this.downloadUrl = downloadUrl;
        this.hadDownloadSize = hadDownloadSize;
        this.downloadProgress = downloadProgress;
        this.version = version;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getFileSize() {
        return fileSize;
    }

    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getTempFilePath() {
        return tempFilePath;
    }

    public void setTempFilePath(String tempFilePath) {
        this.tempFilePath = tempFilePath;
    }

    public String getDownloadUrl() {
        return downloadUrl;
    }

    public void setDownloadUrl(String downloadUrl) {
        this.downloadUrl = downloadUrl;
    }

    public Long getHadDownloadSize() {
        return hadDownloadSize;
    }

    public void setHadDownloadSize(Long hadDownloadSize) {
        this.hadDownloadSize = hadDownloadSize;
    }

    public Integer getDownloadProgress() {
        return downloadProgress;
    }

    public void setDownloadProgress(Integer downloadProgress) {
        this.downloadProgress = downloadProgress;
    }

    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

}
